---
- name: Adding OSPF
  hosts: swapProtocols
  gather_facts: false
  connection: network_cli
  vars_files:
    - ./OSPFvars.yaml

  tasks:
    - name: Adding OSPF
      ios_config:
        src: "OSPF.j2"
