---
- name: Add Pod
  hosts: addDevices
  gather_facts: false
  connection: network_cli
  vars_files:
    - ./addDevicesVars.yaml

  tasks:
    - name: Configuring Devices
      ios_config:
        src: "addDevices.j2"
        
